
// Simple English to Urdu translation dictionary
const englishToUrduDict: { [key: string]: string } = {
  // Common words
  "the": "یہ",
  "and": "اور",
  "is": "ہے",
  "this": "یہ",
  "that": "وہ",
  "with": "کے ساتھ",
  "for": "کے لیے",
  "to": "کو",
  "of": "کا",
  "in": "میں",
  "on": "پر",
  "at": "پر",
  "by": "کے ذریعے",
  "from": "سے",
  "up": "اوپر",
  "about": "کے بارے میں",
  "into": "میں",
  "through": "کے ذریعے",
  "during": "کے دوران",
  "before": "سے پہلے",
  "after": "کے بعد",
  "above": "اوپر",
  "below": "نیچے",
  "over": "اوپر",
  "under": "نیچے",
  
  // Technology terms
  "technology": "ٹیکنالوجی",
  "blog": "بلاگ",
  "post": "پوسٹ",
  "article": "مضمون",
  "content": "مواد",
  "text": "متن",
  "summary": "خلاصہ",
  "translation": "ترجمہ",
  "language": "زبان",
  "english": "انگریزی",
  "urdu": "اردو",
  "artificial": "مصنوعی",
  "intelligence": "ذہانت",
  "application": "ایپلیکیشن",
  "development": "ترقی",
  "software": "سافٹ ویئر",
  "computer": "کمپیوٹر",
  "internet": "انٹرنیٹ",
  "website": "ویب سائٹ",
  "digital": "ڈیجیٹل",
  "online": "آن لائن",
  "modern": "جدید",
  "innovative": "اختراعی",
  "advanced": "ترقی یافتہ",
  "system": "نظام",
  "platform": "پلیٹ فارم",
  "solution": "حل",
  "approach": "طریقہ",
  "strategy": "حکمت عملی",
  "implementation": "نفاذ",
  "practical": "عملی",
  "effective": "مؤثر",
  "efficient": "موثر",
  "performance": "کارکردگی",
  "optimization": "بہتری",
  "user": "صارف",
  "experience": "تجربہ",
  "design": "ڈیزائن",
  "interface": "انٹرفیس",
  "functionality": "فعالیت",
  "feature": "خصوصیت",
  "service": "خدمات",
  "data": "ڈیٹا",
  "information": "معلومات",
  "communication": "رابطہ",
  "network": "نیٹ ورک",
  "security": "سیکیورٹی",
  "privacy": "پرائیویسی",
  "business": "کاروبار",
  "company": "کمپنی",
  "organization": "تنظیم",
  "team": "ٹیم",
  "project": "منصوبہ",
  "work": "کام",
  "job": "نوکری",
  "career": "کیریئر",
  "professional": "پیشہ ور",
  "skill": "مہارت",
  "knowledge": "علم",
  "learning": "تعلیم",
  "education": "تعلیم",
  "training": "تربیت",
  "course": "کورس",
  "tutorial": "ٹیوٹوریل",
  "guide": "رہنمائی",
  "help": "مدد",
  "support": "سپورٹ",
  "problem": "مسئلہ",
  "issue": "مسئلہ",
  "challenge": "چیلنج",
  "opportunity": "موقع",
  "benefit": "فائدہ",
  "advantage": "فائدہ",
  "improvement": "بہتری",
  "success": "کامیابی",
  "result": "نتیجہ",
  "outcome": "نتیجہ",
  "goal": "مقصد",
  "objective": "مقصد",
  "target": "ہدف",
  "purpose": "مقصد",
  "important": "اہم",
  "significant": "اہم",
  "valuable": "قیمتی",
  "useful": "مفید",
  "helpful": "مددگار",
  "necessary": "ضروری",
  "essential": "ضروری",
  "required": "ضروری",
  "needed": "ضروری",
  "available": "دستیاب",
  "accessible": "قابل رسائی",
  "easy": "آسان",
  "simple": "سادہ",
  "complex": "پیچیدہ",
  "difficult": "مشکل",
  "hard": "سخت",
  "fast": "تیز",
  "quick": "تیز",
  "slow": "سست",
  "new": "نیا",
  "old": "پرانا",
  "current": "موجودہ",
  "latest": "تازہ ترین",
  "recent": "حالیہ",
  "future": "مستقبل",
  "past": "ماضی",
  "present": "موجودہ",
  "today": "آج",
  "tomorrow": "کل",
  "yesterday": "کل",
  "now": "اب",
  "then": "پھر",
  "here": "یہاں",
  "there": "وہاں",
  "where": "کہاں",
  "when": "کب",
  "what": "کیا",
  "why": "کیوں",
  "how": "کیسے",
  "who": "کون",
  "which": "کون سا",
  "can": "کر سکتے ہیں",
  "will": "کریں گے",
  "would": "کریں گے",
  "should": "چاہیے",
  "must": "لازمی",
  "may": "ہو سکتا ہے",
  "might": "شاید",
  "could": "کر سکتے ہیں",
  "need": "ضرورت",
  "want": "چاہتے ہیں",
  "like": "پسند",
  "love": "محبت",
  "good": "اچھا",
  "bad": "برا",
  "best": "بہترین",
  "better": "بہتر",
  "great": "عظیم",
  "excellent": "بہترین",
  "amazing": "حیرت انگیز",
  "wonderful": "شاندار",
  "fantastic": "شاندار",
  "perfect": "کامل",
  "right": "صحیح",
  "wrong": "غلط",
  "correct": "صحیح",
  "true": "سچ",
  "false": "جھوٹ",
  "real": "حقیقی",
  "actual": "اصل",
  "main": "اصل",
  "primary": "بنیادی",
  "basic": "بنیادی",
  "fundamental": "بنیادی",
  "key": "اہم",
  "major": "اہم",
  "minor": "چھوٹا",
  "small": "چھوٹا",
  "large": "بڑا",
  "big": "بڑا",
  "huge": "بہت بڑا",
  "tiny": "چھوٹا",
  "long": "لمبا",
  "short": "چھوٹا",
  "high": "اونچا",
  "low": "نیچا",
  "strong": "مضبوط",
  "weak": "کمزور",
  "powerful": "طاقتور",
  "effective": "مؤثر"
};

export const translateText = (text: string): string => {
  const words = text.toLowerCase().split(/\s+/);
  const translatedWords = words.map(word => {
    // Remove punctuation for lookup
    const cleanWord = word.replace(/[^\w]/g, '');
    const translation = englishToUrduDict[cleanWord];
    
    if (translation) {
      // Preserve original punctuation
      return word.replace(cleanWord, translation);
    }
    
    return word;
  });
  
  return translatedWords.join(' ');
};
